#Backtrack config
#Sun May 03 02:59:06 PDT 2026
module.Velocity.setting.FallDamageCheck=true
module.Velocity.hud.shadow=true
module.KeepSprint.hud.visible=true
hud.lineHeight=12
module.AutoClicker.enabled=false
module.Velocity.setting.Chance=80.0
hud.y=0
hud.x=3
module.AutoClicker.setting.Use\ No\ Input=false
module.WTap.hud.y=61
module.AutoClicker.setting.HUD\ Color=BLUE
module.WTap.hud.x=5
module.FullBright.key=0
module.AutoSprint.hud.background=false
module.AutoClicker.setting.Smart\ Attack=false
module.Velocity.setting.PushOnGround=false
module.Velocity.setting.Randomize=true
module.FullBright.hud.background=false
module.KeepSprint.setting.HUD\ Visible=true
module.Velocity.setting.JumpMotionVar=0.04
module.AutoRespawn.hud.background=false
module.Velocity.setting.Mode=JumpReset
module.WTap.enabled=false
module.KeepSprint.setting.Min\ Health=0.0
module.AutoRespawn.setting.HUD\ Visible=true
module.AutoClicker.hud.color=0
module.AutoClicker.hud.background=false
module.WTap.setting.OnlyFacing=true
module.AutoSprint.setting.Hunger\ Check=true
module.Velocity.setting.Debug=false
module.KeepSprint.key=0
module.AutoSprint.setting.Allow\ Sneak=false
module.WTap.hud.shadow=true
module.Velocity.setting.ReverseStrafe=false
module.AutoClicker.setting.HUD\ Shadow=true
module.WTap.key=0
module.Velocity.hud.color=0
module.WTap.setting.MoveBlockDurationMin=0.0
module.Velocity.setting.LegitStrafe=false
module.AutoClicker.hud.shadow=true
module.KeepSprint.hud.y=47
module.AutoSprint.setting.Require\ Forward=true
module.KeepSprint.hud.x=5
module.WTap.setting.HUD\ Background=false
module.AutoRespawn.key=0
module.WTap.setting.StopTicksMin=0.0
module.AutoClicker.setting.HUD\ Background=false
module.AutoSprint.setting.HUD\ Background=false
module.AutoSprint.setting.HUD\ Color=BLUE
module.Velocity.setting.ResetTicks=3.0
module.WTap.setting.MoveBlockStartMin=0.0
module.AutoClicker.setting.Min\ Use\ CPS=8.0
module.AutoRespawn.hud.shadow=true
module.FullBright.setting.HUD\ Visible=true
module.AutoRespawn.setting.HUD\ Color=BLUE
module.AutoClicker.setting.Press\ Delay=0.0
module.FullBright.hud.shadow=true
module.AutoClicker.setting.Attack\ No\ Input=false
module.Velocity.setting.DelayMax=3.0
module.FullBright.hud.y=19
module.FullBright.hud.x=5
module.WTap.setting.OnlyOnGround=true
module.AutoClicker.setting.Min\ CPS=13.0
module.WTap.hud.color=0
module.AutoClicker.setting.HUD\ Visible=true
module.Velocity.hud.y=89
module.Velocity.hud.x=5
module.AutoSprint.setting.PostHurt\ Ticks=10.0
module.Velocity.setting.PushStart=9.0
module.FullBright.setting.Gamma=20.0
module.Velocity.setting.Push=1.1
module.FullBright.setting.HUD\ Shadow=true
module.AutoClicker.setting.Max\ CPS=15.0
module.WTap.setting.ReSprintDelayMax=2.0
module.AutoRespawn.setting.HUD\ Background=false
module.AutoSprint.hud.y=5
module.WTap.setting.PacketDelayMax=2.0
module.AutoSprint.hud.x=5
module.KeepSprint.enabled=false
module.WTap.setting.HurtTimeThreshold=10.0
module.AutoClicker.setting.Use\ Only\ Block=false
module.Velocity.setting.XZ=2.0
module.KeepSprint.setting.Only\ On\ Hit=true
module.Velocity.key=45
hud.shadow=true
module.WTap.hud.visible=true
module.AutoSprint.hud.visible=true
module.FullBright.setting.HUD\ Background=false
module.AutoSprint.key=0
module.AutoRespawn.hud.visible=true
module.WTap.hud.background=false
module.AutoClicker.key=47
module.KeepSprint.hud.color=0
hud.anchorIndex=0
module.FullBright.hud.visible=true
module.Velocity.setting.Y=0.0
module.AutoSprint.setting.HUD\ Visible=true
module.AutoSprint.enabled=true
module.AutoSprint.setting.HUD\ Shadow=true
module.WTap.setting.HUD\ Color=BLUE
module.AutoClicker.setting.Ignore\ Blocks=false
module.AutoClicker.hud.visible=true
module.KeepSprint.hud.shadow=true
module.WTap.setting.NotInWater=true
module.AutoSprint.setting.Mode=Intave
module.WTap.setting.HUD\ Visible=true
module.WTap.setting.HUD\ Shadow=true
module.Velocity.setting.IgnoreExplosion=true
module.WTap.setting.Chance=80.0
hud.colorIndex=0
module.AutoClicker.hud.y=75
module.AutoClicker.hud.x=5
module.FullBright.enabled=false
module.AutoSprint.hud.shadow=true
module.AutoRespawn.setting.HUD\ Shadow=true
gui.y=90
gui.x=8
module.Velocity.setting.DelayMin=1.0
module.Velocity.setting.MaxDistance=1.0
module.AutoClicker.setting.Only\ On\ Target=true
hud.textMode=1
module.Velocity.setting.PushEnd=2.0
module.FullBright.hud.color=0
module.Velocity.setting.ReverseStart=5.86
module.AutoClicker.setting.Use\ Clicker=false
module.KeepSprint.hud.background=false
module.AutoClicker.setting.Max\ Use\ CPS=12.0
module.Velocity.enabled=false
module.FullBright.setting.HUD\ Color=BLUE
module.AutoRespawn.hud.color=0
module.WTap.setting.Mode=Packet
hud.visible=true
module.AutoRespawn.hud.y=33
module.AutoRespawn.hud.x=5
module.WTap.setting.MoveBlockDurationMax=2.0
module.KeepSprint.setting.HUD\ Color=BLUE
module.WTap.setting.ReSprintDelayMin=1.0
module.Velocity.hud.visible=true
module.KeepSprint.setting.HUD\ Background=false
module.WTap.setting.StopTicksMax=1.0
module.Velocity.hud.background=false
module.Velocity.setting.TickZeroHurtTime=4.0
module.WTap.setting.PacketDelayMin=1.0
module.AutoSprint.hud.color=0
hud.background=true
module.Velocity.setting.Cooldown=14.0
module.AutoRespawn.enabled=false
module.WTap.setting.MoveBlockStartMax=1.0
module.KeepSprint.setting.HUD\ Shadow=true
